version: "3.8"

services:
  contao:
    image: splintnet/dockerized-contao
    volumes:
      - "app:/application"
      - "files:/application/files"
      - "logs:/application/var/logs"
      - "assets:/application/assets"
    external_links:
      - db
    networks:
      - db
      - traefik

  nginx:
    image: nginx:alpine
    volumes:
      - app:/application
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      traefik:
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.contao.rule=Host(`your-site.com`)"
      # - "traefik.http.routers.contao.tls.certresolver=myhttpchallenge"
      # - "traefik.http.routers.contao.entrypoints=websecure"
      # - "traefik.http.routers.contao.tls=true"

volumes:
  app:
  files:
  logs:
  assets:

networks:
  db:
    external: true
  traefik:
    external: true
